[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "school require window ski camera helmet usual good home valve spin rural hero glove execute scrub coral round beyond spread morning leisure vendor want"
